name: Release
on:
    push:
        tags:
            - *
jobs:
    build:
        runs-on: ubuntu-latest
        steps:
            - uses: actions/checkout@v2
            - name: Setup go
              uses: actions/setup-go@v1
              with:
                  go-version: 1.14
            - run: go build .
            - uses: ncipollo/release-action@v1
              with:
                  artifacts: "k6"
                  token: ${{ secrets.GITHUB_TOKEN }}
