name: Bump version
on:
    push:
        branches:
            - master
jobs:
    build:
        runs-on: ubuntu-latest
        steps:
            - uses: actions/checkout@v2
            - name: Bump version and push tag
              id: tag_version
              uses: mathieudutour/github-tag-action@v5.5
              with:
                  github_token: ${{ secrets.GITHUB_TOKEN }}
            - name: Setup go
              uses: actions/setup-go@v1
              with:
                  go-version: 1.14
            - run: go build .
            - uses: ncipollo/release-action@v1
              with:
                  artifacts: "release.tar.gz,k6"
                  token: ${{ secrets.GITHUB_TOKEN }}
